<a href="https://colab.research.google.com/github/DirksGAN/Pytorch/blob/main/First%20steps%20with%20pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import torch
import numpy as np
import matplotlib

In [33]:
a = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(4.0, requires_grad=True)
c = torch.tensor(5.0, requires_grad=True)

In [34]:
print(a, b, c)

tensor(3., requires_grad=True) tensor(4., requires_grad=True) tensor(5., requires_grad=True)


In [41]:
a2 = 3*a + 1*b + c
print(a2)
print(a2.backward())
print(a2.grad)

tensor(18., grad_fn=<AddBackward0>)
None
None


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  after removing the cwd from sys.path.


In [44]:
import PIL as plt

In [49]:
#Gebe mir einen random tensor mit 3 Einträgen aus     
newA = torch.rand(3)
print(newA)

tensor([0.8075, 0.0447, 0.6077])


In [50]:
# Gebe mir einen zufälligen Tensor mit zwei Dimensionen (3*10) aus
newB = torch.rand(3,10)
print(newB)

tensor([[0.4170, 0.3451, 0.6725, 0.9062, 0.5858, 0.5682, 0.7795, 0.0700, 0.9441,
         0.6155],
        [0.6227, 0.7617, 0.1253, 0.5726, 0.1257, 0.9037, 0.9600, 0.5538, 0.6713,
         0.6975],
        [0.4969, 0.9091, 0.8914, 0.6702, 0.8236, 0.2931, 0.9191, 0.4690, 0.9470,
         0.2275]])


In [52]:
# Warum Pytorch verwenden statt Tensorflow / Keras?
'''
1.) Pytorch ist state of the art, wie man im Englischen sagt. 
2.) Der Code ist sehr einfach lesbar
3.) Bei Tensorflow nutzt man eher Keras statt native Tensorflow
4.) Pytorch ist von Facebook -> Von einem kompetenten Team
5.) Pytorch ist High Level 
6.) In Tensorflow muss man immer gleiche Dateigrößen eingeben
'''

'\n1.) Pytorch ist state of the art, wie man im Englischen sagt. \n2.) Der Code ist sehr einfach lesbar\n3.) Bei Tensorflow nutzt man eher Keras statt native Tensorflow\n4.) Pytorch ist von Facebook -> Von einem kompetenten Team\n5.) Pytorch ist High Level \n6.) In Tensorflow muss man immer gleiche Dateigrößen eingeben\n'

In [65]:
# Hier wollen wir uns mit Tensoren beschäftigen. Ein Tensor ist "eine Variable" in Pytorch
# Ein Tensor ist eine Matrix

meinTensor = torch.rand(2,2)*10
print(meinTensor)

mt2 = torch.tensor(5.0)
print(mt2)

mt3 = torch.tensor(3)
print(mt3)

mt4 = torch.randn(3)
print(mt4)

mt5 = torch.zeros_like(meinTensor)
print(mt5)
print(meinTensor)
print(meinTensor.size())

ergebnis1 = torch.add(meinTensor, mt5)
print(ergebnis1)

mt6 = torch.tensor([1,2,3,4,5])
print(mt6)

tensor([[4.4447, 3.1352],
        [2.9455, 2.6822]])
tensor(5.)
tensor(3)
tensor([-0.1915, -1.2219,  0.1528])
tensor([[0., 0.],
        [0., 0.]])
tensor([[4.4447, 3.1352],
        [2.9455, 2.6822]])
torch.Size([2, 2])
tensor([[4.4447, 3.1352],
        [2.9455, 2.6822]])
tensor([1, 2, 3, 4, 5])


In [68]:
t1 = torch.tensor([[1,2,3],[1,2,3]])
print(t1)

if torch.cuda.is_available():
  t1 = t1.cuda()
print(t1)

tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3]])


In [89]:
# Das erste eigene Netzwerk
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import torch.optim as optim

class MeinNetz(nn.Module):
  def __init__(self):
    super(MeinNetz, self).__init__()
    self.lin1 = nn.Linear(10,10)
    self.lin2 = nn.Linear(10,10)

  def forward(self, x):
    x = F.relu(self.lin1(x))
    x = self.lin2(x)
    return x

  def num_flat_features(self, x):
    size = x.size()[1:]
    num = 1
    for i in size:
      num *= i
    return num

netz = MeinNetz()
for i in range(100):

  input = Variable(torch.randn(10,10))
  out = netz(input)

  x = [0,0,0,0,0,0,0,0,0,0]
  target= Variable(torch.Tensor([x for _ in range(10)]))
  criterion = nn.MSELoss()
  loss = criterion(out, target)
  print(loss)

  netz.zero_grad()
  loss.backward(retain_graph=True)
  optimizer = optim.Adam(netz.parameters(), lr=0.01)
  optimizer.step()

  # Neuronale Netzwerke haben sehr viel mit ausprobieren zu tun.

print(out)

tensor(0.1574, grad_fn=<MseLossBackward>)
tensor(0.1051, grad_fn=<MseLossBackward>)
tensor(0.0845, grad_fn=<MseLossBackward>)
tensor(0.0749, grad_fn=<MseLossBackward>)
tensor(0.0462, grad_fn=<MseLossBackward>)
tensor(0.0419, grad_fn=<MseLossBackward>)
tensor(0.0303, grad_fn=<MseLossBackward>)
tensor(0.0274, grad_fn=<MseLossBackward>)
tensor(0.0248, grad_fn=<MseLossBackward>)
tensor(0.0155, grad_fn=<MseLossBackward>)
tensor(0.0270, grad_fn=<MseLossBackward>)
tensor(0.0175, grad_fn=<MseLossBackward>)
tensor(0.0164, grad_fn=<MseLossBackward>)
tensor(0.0133, grad_fn=<MseLossBackward>)
tensor(0.0161, grad_fn=<MseLossBackward>)
tensor(0.0137, grad_fn=<MseLossBackward>)
tensor(0.0089, grad_fn=<MseLossBackward>)
tensor(0.0095, grad_fn=<MseLossBackward>)
tensor(0.0101, grad_fn=<MseLossBackward>)
tensor(0.0096, grad_fn=<MseLossBackward>)
tensor(0.0056, grad_fn=<MseLossBackward>)
tensor(0.0062, grad_fn=<MseLossBackward>)
tensor(0.0060, grad_fn=<MseLossBackward>)
tensor(0.0050, grad_fn=<MseLossBac